# https://cloud.google.com/appengine/docs/the-appengine-environments#comparing_high-level_features
# https://cloud.google.com/appengine/docs/standard

runtime: java17
instance_class: F2

env: flex #flex is environment needed for websocket

# Enable WebSocket support
network:
  session_affinity: true

# Request handlers
handlers:
  - url: /ws(/.*)?
    script: auto
    secure: always
  - url: /.*
    script: auto
    secure: always