# https://cloud.google.com/appengine/docs/the-appengine-environments#comparing_high-level_features
# https://cloud.google.com/appengine/docs/standard

runtime: custom
instance_class: F2


env: flex
automatic_scaling:
  min_num_instances: 1
  max_num_instances: 1

network: 
  session_affinity: true
